<?php
$dictionary['vedic_Candidates']['fields']['communication_comments']['name']='communication_comments';
$dictionary['vedic_Candidates']['fields']['communication_comments']['vname']='Comments';
$dictionary['vedic_Candidates']['fields']['communication_comments']['type']='text';
$dictionary['vedic_Candidates']['fields']['communication_comments']['importable']=true;
$dictionary['vedic_Candidates']['fields']['communication_comments']['mass_update']=true;
$dictionary['vedic_Candidates']['fields']['communication_comments']['audited']=true;
$dictionary['vedic_Candidates']['fields']['communication_comments']['inline_edit']=true;
$dictionary['vedic_Candidates']['fields']['communication_comments']['rows']='4';
$dictionary['vedic_Candidates']['fields']['communication_comments']['cols']='20';
$dictionary['vedic_Candidates']['fields']['communication_comments']['merge_filter']='disabled';
?>