<?php
$dictionary['vedic_Candidates']['fields']['technical_comments']['name']='technical_comments';
$dictionary['vedic_Candidates']['fields']['technical_comments']['vname']='Comments';
$dictionary['vedic_Candidates']['fields']['technical_comments']['type']='text';
$dictionary['vedic_Candidates']['fields']['technical_comments']['importable']=true;
$dictionary['vedic_Candidates']['fields']['technical_comments']['mass_update']=true;
$dictionary['vedic_Candidates']['fields']['technical_comments']['audited']=true;
$dictionary['vedic_Candidates']['fields']['technical_comments']['inline_edit']=true;
$dictionary['vedic_Candidates']['fields']['technical_comments']['rows']='4';
$dictionary['vedic_Candidates']['fields']['technical_comments']['cols']='20';
$dictionary['vedic_Candidates']['fields']['technical_comments']['merge_filter']='disabled';
?>