<?php
$dictionary['vedic_Candidates']['fields']['functional_comments']['name']='functional_comments';
$dictionary['vedic_Candidates']['fields']['functional_comments']['vname']='Comments';
$dictionary['vedic_Candidates']['fields']['functional_comments']['type']='text';
$dictionary['vedic_Candidates']['fields']['functional_comments']['importable']=true;
$dictionary['vedic_Candidates']['fields']['functional_comments']['mass_update']=true;
$dictionary['vedic_Candidates']['fields']['functional_comments']['audited']=true;
$dictionary['vedic_Candidates']['fields']['functional_comments']['inline_edit']=true;
$dictionary['vedic_Candidates']['fields']['functional_comments']['rows']='4';
$dictionary['vedic_Candidates']['fields']['functional_comments']['cols']='20';
$dictionary['vedic_Candidates']['fields']['functional_comments']['merge_filter']='disabled';
?>