<?php
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['name']='memo';
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['vname']='LBL_MEMO';
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['type']='text';
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['importable']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['mass_update']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['audited']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['inline_edit']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['rows']='6';
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['cols']='80';
$dictionary['vedic_GCPayroll_Deductions']['fields']['memo']['merge_filter']='disabled';
?>
