 <?php
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['name']='pay_date';
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['vname']='LBL_PAY_DATE';
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['type']='date';
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['importable']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['mass_update']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['audited']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['inline_edit']=true;
$dictionary['vedic_GCPayroll_Deductions']['fields']['pay_date']['merge_filter']='disabled';
?>
