<?php
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['required']=true;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['source']='non-db';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['name']='project_manager';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['vname']='LBL_PROJECT_MANAGER';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['type']='relate';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['massupdate']=0;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['no_default']=false;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['comments']='';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['help']='';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['importable']='true';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['duplicate_merge']='disabled';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['duplicate_merge_dom_value']='0';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['audited']=true;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['reportable']=true;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['unified_search']=false;
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['merge_filter']='disabled';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['len']='255';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['size']='30';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['id_name']='project_manager_id';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['ext2']='Users';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['module']='Users';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['rname']='name';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['quicksearch']='enabled';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['studio']='visible';
$dictionary['vedic_Solutions_Projects']['fields']['project_manager']['inline_edit']=true;
?>
