<?php
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['name']='billing_type';
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['vname']='LBL_BILLING_TYPE';
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['type']='enum';
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['options']='solutions_billing_type';
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['importable']=true;
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['mass_update']=true;
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['audited']=true;
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['inline_edit']=true;
$dictionary['vedic_Solutions_Projects']['fields']['billing_type']['merge_filter']='disabled';
?>
