<?php
$dictionary['vedic_Solutions_Projects']['fields']['client']['required']=true;
$dictionary['vedic_Solutions_Projects']['fields']['client']['source']='non-db';
$dictionary['vedic_Solutions_Projects']['fields']['client']['name']='client';
$dictionary['vedic_Solutions_Projects']['fields']['client']['vname']='LBL_CLIENT';
$dictionary['vedic_Solutions_Projects']['fields']['client']['type']='relate';
$dictionary['vedic_Solutions_Projects']['fields']['client']['massupdate']=0;
$dictionary['vedic_Solutions_Projects']['fields']['client']['no_default']=false;
$dictionary['vedic_Solutions_Projects']['fields']['client']['comments']='';
$dictionary['vedic_Solutions_Projects']['fields']['client']['help']='';
$dictionary['vedic_Solutions_Projects']['fields']['client']['importable']='true';
$dictionary['vedic_Solutions_Projects']['fields']['client']['duplicate_merge']='disabled';
$dictionary['vedic_Solutions_Projects']['fields']['client']['duplicate_merge_dom_value']='0';
$dictionary['vedic_Solutions_Projects']['fields']['client']['audited']=true;
$dictionary['vedic_Solutions_Projects']['fields']['client']['reportable']=true;
$dictionary['vedic_Solutions_Projects']['fields']['client']['unified_search']=false;
$dictionary['vedic_Solutions_Projects']['fields']['client']['merge_filter']='disabled';
$dictionary['vedic_Solutions_Projects']['fields']['client']['len']='255';
$dictionary['vedic_Solutions_Projects']['fields']['client']['size']='30';
$dictionary['vedic_Solutions_Projects']['fields']['client']['id_name']='client_id';
$dictionary['vedic_Solutions_Projects']['fields']['client']['ext2']='Accounts';
$dictionary['vedic_Solutions_Projects']['fields']['client']['module']='Accounts';
$dictionary['vedic_Solutions_Projects']['fields']['client']['rname']='name';
$dictionary['vedic_Solutions_Projects']['fields']['client']['quicksearch']='enabled';
$dictionary['vedic_Solutions_Projects']['fields']['client']['studio']='visible';
$dictionary['vedic_Solutions_Projects']['fields']['client']['inline_edit']=true;
?>

