<?php
$dictionary['User']['fields']['contract']['required']=false;
$dictionary['User']['fields']['contract']['source']='non-db';
$dictionary['User']['fields']['contract']['name']='contract';
$dictionary['User']['fields']['contract']['vname']='LBL_CONTRACT';
$dictionary['User']['fields']['contract']['type']='relate';
$dictionary['User']['fields']['contract']['massupdate']=0;
$dictionary['User']['fields']['contract']['no_default']=false;
$dictionary['User']['fields']['contract']['comments']='';
$dictionary['User']['fields']['contract']['help']='';
$dictionary['User']['fields']['contract']['importable']='true';
$dictionary['User']['fields']['contract']['duplicate_merge']='disabled';
$dictionary['User']['fields']['contract']['duplicate_merge_dom_value']='0';
$dictionary['User']['fields']['contract']['audited']=true;
$dictionary['User']['fields']['contract']['reportable']=true;
$dictionary['User']['fields']['contract']['unified_search']=false;
$dictionary['User']['fields']['contract']['merge_filter']='disabled';
$dictionary['User']['fields']['contract']['len']='255';
$dictionary['User']['fields']['contract']['size']='30';
$dictionary['User']['fields']['contract']['id_name']='contract_id';
$dictionary['User']['fields']['contract']['ext2']='AOS_Contracts';
$dictionary['User']['fields']['contract']['module']='AOS_Contracts';
$dictionary['User']['fields']['contract']['rname']='name';
$dictionary['User']['fields']['contract']['quicksearch']='enabled';
$dictionary['User']['fields']['contract']['studio']='visible';
$dictionary['User']['fields']['contract']['inline_edit']=true;
?>

