<?php
$dictionary['vedic_GC']['fields']['swa']['name']='swa';
$dictionary['vedic_GC']['fields']['swa']['vname']='LBL_SWA';
$dictionary['vedic_GC']['fields']['swa']['type']='radioenum';
$dictionary['vedic_GC']['fields']['swa']['dbType']='enum';
$dictionary['vedic_GC']['fields']['swa']['options']='gc_list';
$dictionary['vedic_GC']['fields']['swa']['importable']=true;
$dictionary['vedic_GC']['fields']['swa']['mass_update']=true;
$dictionary['vedic_GC']['fields']['swa']['audited']=true;
$dictionary['vedic_GC']['fields']['swa']['inline_edit']=false;
$dictionary['vedic_GC']['fields']['swa']['merge_filter']='disabled';
?>
