<?php
$dictionary['vedic_GC']['fields']['erp']['name']='erp';
$dictionary['vedic_GC']['fields']['erp']['vname']='LBL_ERP';
$dictionary['vedic_GC']['fields']['erp']['type']='radioenum';
$dictionary['vedic_GC']['fields']['erp']['dbType']='enum';
$dictionary['vedic_GC']['fields']['erp']['options']='gc_list';
$dictionary['vedic_GC']['fields']['erp']['importable']=true;
$dictionary['vedic_GC']['fields']['erp']['mass_update']=true;
$dictionary['vedic_GC']['fields']['erp']['audited']=true;
$dictionary['vedic_GC']['fields']['erp']['inline_edit']=false;
$dictionary['vedic_GC']['fields']['erp']['merge_filter']='disabled';
?>
